---
- name: "deploy | php artisan migrate --force | {{ deployment_directory }}"
  shell: php artisan migrate --force
  args:
    chdir: "{{ deployment_directory }}/releases/{{ release_time }}/"
  when: requires_migration is defined and requires_migration
  run_once: true