---
- name: "deploy | php artisan migrate --force | {{ deployment_directory }}"
  shell: php artisan migrate --force
  args:
    chdir: "{{ deployment_directory }}/releases/{{ release_time }}/"
  when:
    - requires_migration is defined
    - requires_migration | bool
    - db_migration is defined and db_migration == "yes"
#  run_once: true