- name: "deploy | upload {{ application_directory }}/build/dist/deploy.tar.gz to {{ deployment_directory }}/releases/{{ release_time }}/"
  synchronize:
    src: "{{ application_directory }}/build/dist/deploy.tar.gz"
    dest: "{{ deployment_directory }}/releases/{{ release_time }}/"
    rsync_path: SUDO_ASKPASS=/usr/bin/ssh-askpass sudo -A /usr/bin/rsync
    compress: yes
    checksum: yes
    delete: yes
    recursive: yes
    links: yes
    mode: push
    rsync_opts:
      - "--no-motd"
      - "--omit-dir-times"