---
- include: 01-create-release-folder.yml
- include: 02-upload-application-archive.yml
- include: 03-uncompress-application-archive.yml
- include: 04-remove-application-archive.yml
- include: 05-set-file-permissions.yml
- include: 06-link-shared-content.yml

### Run database migrations if required
- include: laravel/db-migration.yml
  when:
    - requires_migration | bool
    - deploy_type == "laravel"

- include: symfony/db-migration.yml
  when:
    - requires_migration | bool
    - deploy_type == "symfony"

### Warmup application - setup caches
- include: symfony/warmup.yml
  when:
    - deploy_type == "symfony"

- include: laravel/warmup.yml
  when:
    - deploy_type == "laravel"

- include: 07-change-current-symlink.yml

### Restart worker services when defined
- include: laravel/restart-worker.yml
  when:
    - deploy_type == "laravel"

### Plesk? Lets cheat!
- include: 08-plesk-hack.yml
  when:
    - server_software is defined
    - server_software == "plesk"

# The tasks defined in this configuration are used for application specific actions after the deployment is done. E.g. run an artisan task or clear opcache
- include: 999-application-specific-tasks.yml

# Restart webserver and php FPM
- name: deploy | restart httpd
  service:
    name: "{{ httpd_service_name }}"
    state: restarted

- name: deploy | restart php-fpm
  service:
    name: "{{ php_fpm_service_name }}"
    state: restarted